# Generated by Django 5.2.8 on 2026-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('microfinance', 'Microfinance'), ('real_estate', 'Real Estate'), ('all', 'All')], default='inventory', max_length=255),
        ),
    ]
