# Generated by Django 5.2.8 on 2026-04-18 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organization.branch'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'last_name', 'first_name'], name='customers_c_branch__e32537_idx'),
        ),
    ]
