# Generated by Django 5.2.8 on 2025-11-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization assigned to this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.organization'),
        ),
    ]
