# Generated by Django 5.2.8 on 2025-11-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_organization_user_branch_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_iam_user',
            field=models.BooleanField(default=False),
        ),
    ]
