# Generated by Django 5.2.8 on 2025-11-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_iam_user'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization assigned to this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='organization.organization'),
        ),
    ]
