# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_product_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
