# Generated by Django 5.2.8 on 2025-11-23 17:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='KPI name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this KPI measures')),
                ('source_type', models.CharField(choices=[('aggregate', 'System Aggregate'), ('manual', 'Manual Entry')], help_text='How this KPI is tracked - aggregate from system or manual entry', max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Tracking period for this KPI', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target value for this KPI', max_digits=15, null=True)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable value', max_digits=15, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum acceptable value', max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement (e.g., 'count', 'percentage', 'USD', 'hours')", max_length=50)),
                ('aggregate_query', models.TextField(blank=True, help_text='Query or configuration for system aggregate KPIs')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this KPI is currently being tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this KPI is specific to (null for organization-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organization.branch')),
                ('created_by', models.ForeignKey(help_text='User who created this KPI (must have supervisor role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this KPI belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organization.organization')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_resolved', 'Ticket Resolved'), ('message_sent', 'Message Sent'), ('user_created', 'User Created'), ('custom', 'Custom Action')], help_text='Type of action being tracked', max_length=50)),
                ('action_data', models.JSONField(blank=True, default=dict, help_text='Additional data about the action')),
                ('related_entity_type', models.CharField(blank=True, help_text="Type of related entity (e.g., 'Ticket', 'Message')", max_length=100)),
                ('related_entity_id', models.CharField(blank=True, help_text='ID of related entity', max_length=100)),
                ('contribution_value', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Value this action contributes to the KPI', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(help_text='KPI this action contributes to', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_actions', to='kpis.kpi')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Action',
                'verbose_name_plural': 'KPI Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, help_text='Actual value for this KPI entry', max_digits=15)),
                ('period_start', models.DateField(help_text='Start date of the tracking period')),
                ('period_end', models.DateField(help_text='End date of the tracking period')),
                ('is_calculated', models.BooleanField(default=False, help_text='Whether this value was calculated by the system or entered manually')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this entry')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, help_text='User who entered this value (null if calculated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_entries', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(help_text='KPI this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kpis.kpi')),
            ],
            options={
                'verbose_name': 'KPI Entry',
                'verbose_name_plural': 'KPI Entries',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['organization', 'is_active'], name='kpis_kpi_organiz_678752_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['branch', 'is_active'], name='kpis_kpi_branch__643a04_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['source_type', 'period'], name='kpis_kpi_source__5e5c40_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiaction',
            index=models.Index(fields=['kpi', 'action_type'], name='kpis_kpiact_kpi_id_d9db09_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiaction',
            index=models.Index(fields=['user', 'created_at'], name='kpis_kpiact_user_id_c15f16_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiaction',
            index=models.Index(fields=['related_entity_type', 'related_entity_id'], name='kpis_kpiact_related_48d9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='kpientry',
            index=models.Index(fields=['kpi', 'period_start'], name='kpis_kpient_kpi_id_808ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='kpientry',
            index=models.Index(fields=['period_start', 'period_end'], name='kpis_kpient_period__ad2f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='kpientry',
            index=models.Index(fields=['is_calculated'], name='kpis_kpient_is_calc_c9c034_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpientry',
            unique_together={('kpi', 'period_start', 'period_end')},
        ),
    ]
