# Generated by Django 5.2.8 on 2025-11-23 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_module_organization'),
        ('kpis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('role', 'Role Assignment'), ('user', 'Individual Assignment')], help_text='Type of assignment - role or individual user', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment (supervisor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(help_text='KPI being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpis.kpi')),
                ('role', models.ForeignKey(blank=True, help_text="Role assigned to this KPI (if assignment_type is 'role')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='accounts.role')),
                ('user', models.ForeignKey(blank=True, help_text="User assigned to this KPI (if assignment_type is 'user')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Assignment',
                'verbose_name_plural': 'KPI Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(help_text='Start date of the reporting period')),
                ('period_end', models.DateField(help_text='End date of the reporting period')),
                ('reported_value', models.DecimalField(decimal_places=2, help_text='Value reported by the user', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Notes or explanation about this report')),
                ('supporting_documentation', models.JSONField(blank=True, default=dict, help_text='Supporting documentation or evidence')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status of this report', max_length=20)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from supervisor on approval/rejection')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the report was submitted', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor who approved/rejected this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kpi_reports', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(help_text='KPI assignment this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kpis.kpiassignment')),
                ('kpi', models.ForeignKey(help_text='KPI being reported on', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kpis.kpi')),
                ('reported_by', models.ForeignKey(help_text='User who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Report',
                'verbose_name_plural': 'KPI Reports',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['kpi', 'assignment_type', 'is_active'], name='kpis_kpiass_kpi_id_660757_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['role', 'is_active'], name='kpis_kpiass_role_id_d1a9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['user', 'is_active'], name='kpis_kpiass_user_id_1f3aa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpiassignment',
            unique_together={('kpi', 'role'), ('kpi', 'user')},
        ),
        migrations.AddIndex(
            model_name='kpireport',
            index=models.Index(fields=['kpi', 'status'], name='kpis_kpirep_kpi_id_16cf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireport',
            index=models.Index(fields=['assignment', 'status'], name='kpis_kpirep_assignm_5a9531_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireport',
            index=models.Index(fields=['reported_by', 'status'], name='kpis_kpirep_reporte_29e036_idx'),
        ),
        migrations.AddIndex(
            model_name='kpireport',
            index=models.Index(fields=['period_start', 'period_end'], name='kpis_kpirep_period__720674_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpireport',
            unique_together={('assignment', 'period_start', 'period_end')},
        ),
    ]
