# Generated by Django 5.2.8 on 2026-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_kpiassignment_kpireport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='kpis.kpi'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='formula',
            field=models.TextField(blank=True, help_text='Optional expression/DSL for composite or computed KPIs'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='is_composite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi',
            name='scoring_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kpi',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
