# Generated by Django 5.2.8 on 2026-05-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='localpurchaseorder',
            new_name='suppliers_l_organiz_b7fddd_idx',
            old_name='suppliers_l_org_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='localpurchaseorder',
            new_name='suppliers_l_branch__0e047e_idx',
            old_name='suppliers_l_branch_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='localpurchaseorder',
            new_name='suppliers_l_supplie_30d6b2_idx',
            old_name='suppliers_l_supp_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='localpurchaseorderitem',
            new_name='suppliers_l_lpo_id_a63131_idx',
            old_name='suppliers_li_lpo_line_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='suppliers_s_organiz_57b65f_idx',
            old_name='suppliers_s_organiz_6f_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='suppliers_s_branch__845795_idx',
            old_name='suppliers_s_branch__idx',
        ),
    ]
