# Generated by Django 5.2.8 on 2026-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_suppliers_l_org_stat_idx_suppliers_l_organiz_b7fddd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorderitem',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localpurchaseorderitem',
            name='delivered_status',
            field=models.BooleanField(default=False),
        ),
    ]
