# Generated by Django 5.2.8 on 2026-05-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_remove_localpurchaseorderitem_line_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localpurchaseorderitem',
            options={'ordering': ['lpo', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='localpurchaseorderitem',
            name='suppliers_l_lpo_id_a63131_idx',
        ),
    ]
