# Generated by Django 5.2.8 on 2025-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_ticket_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
