# Generated by Django 5.2.8 on 2025-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_ticket_closing_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='crm_ticketc_name_415370_idx')],
            },
        ),
    ]
