# Generated by Django 5.2.8 on 2026-04-17 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0001_initial'),
        ('jobs', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='financials__organiz_482453_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['job'], name='financials__job_id_1825a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['organization', 'status'], name='financials__organiz_737459_idx'),
        ),
    ]
