# Generated by Django 5.2.8 on 2026-04-18 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_initial'),
        ('jobs', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'status'], name='financials__branch__4dc9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['branch', 'status'], name='financials__branch__ceae59_idx'),
        ),
    ]
