# Generated by Django 5.2.8 on 2026-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_invoice_branch_requisition_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile money'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
