# Generated by Django 5.2.8 on 2026-05-13 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_invoicepayment_method_and_more'),
        ('ledgers', '0001_initial'),
        ('organization', '0003_alter_organization_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Unique slug used in API calls, e.g. 'mobile_money'.", max_length=50)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank / Direct Debit'), ('card', 'Card / POS'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], help_text='Determines which GL code range is used when the account is created.', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Dedicated GL account created atomically with this payment method.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='ledgers.account')),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for system-wide defaults available to all branches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organization.branch')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'financials_payment_method',
                'ordering': ['name'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(help_text="e.g. 'Stanbic Bank Uganda'", max_length=100)),
                ('account_name', models.CharField(help_text="e.g. 'Main Operating Account'", max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organization.branch')),
                ('payment_method', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='financials.paymentmethod')),
            ],
            options={
                'db_table': 'financials_bank_account',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='financials.paymentmethod'),
        ),
    ]
