# Generated by Django 5.2.8 on 2025-11-29 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='info_catego_name_5a1732_idx'), models.Index(fields=['slug'], name='info_catego_slug_6a780f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='info_tag_name_93b58f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sops', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sops', to='info.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sops', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sops', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='sops', to='info.tag')),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='info_sop_title_a8a1c4_idx'), models.Index(fields=['status', 'is_published'], name='info_sop_status_a95e2f_idx'), models.Index(fields=['category'], name='info_sop_categor_aa848c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('policy_reference', models.CharField(blank=True, help_text='Reference to the official policy document', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_explanations', to='info.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_explanations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policy_explanations', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='policy_explanations', to='info.tag')),
            ],
            options={
                'verbose_name': 'Policy Explanation',
                'verbose_name_plural': 'Policy Explanations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='info_policy_title_53801b_idx'), models.Index(fields=['is_published', 'created_at'], name='info_policy_is_publ_749f67_idx'), models.Index(fields=['category'], name='info_policy_categor_602d6e_idx'), models.Index(fields=['policy_reference'], name='info_policy_policy__c0b7f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='info.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='faqs', to='info.tag')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question'], name='info_faq_questio_170513_idx'), models.Index(fields=['is_published', 'created_at'], name='info_faq_is_publ_0bff13_idx'), models.Index(fields=['category'], name='info_faq_categor_2d6b26_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the article')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_read_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_articles', to='info.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='training_articles', to='info.tag')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_training_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Article',
                'verbose_name_plural': 'Training Articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='info_traini_title_3b3493_idx'), models.Index(fields=['is_published', 'created_at'], name='info_traini_is_publ_75d815_idx'), models.Index(fields=['category'], name='info_traini_categor_fd1a24_idx'), models.Index(fields=['difficulty_level'], name='info_traini_difficu_f6ffb5_idx')],
            },
        ),
    ]
