# Generated by Django 5.2.8 on 2025-11-30 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingarticle',
            name='is_compulsory',
            field=models.BooleanField(default=False, help_text='Whether this training article is compulsory for users to read'),
        ),
        migrations.AddField(
            model_name='trainingarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingArticleRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, help_text='When the user read the article')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed reading the article (if tracked)', null=True)),
                ('training_article', models.ForeignKey(help_text='Training article that was read', on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='info.trainingarticle')),
                ('user', models.ForeignKey(help_text='User who read the training article', on_delete=django.db.models.deletion.CASCADE, related_name='training_article_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Article Read',
                'verbose_name_plural': 'Training Article Reads',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'training_article'], name='info_traini_user_id_9e1b54_idx'), models.Index(fields=['read_at'], name='info_traini_read_at_0cf3c9_idx'), models.Index(fields=['user', 'read_at'], name='info_traini_user_id_875a29_idx')],
                'unique_together': {('user', 'training_article')},
            },
        ),
    ]
