# Generated by Django 5.2.8 on 2026-05-09 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('expense_type', models.CharField(choices=[('operational', 'Operational'), ('supplier', 'Supplier Invoice'), ('employee_reimbursement', 'Employee Reimbursement'), ('prepaid', 'Prepaid Expense'), ('accrual', 'Accrued Expense'), ('capital', 'Capitalizable Expense'), ('deferred', 'Deferred Expense'), ('corporate_card', 'Corporate Card')], max_length=32)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_capitalizable', models.BooleanField(default=False)),
                ('is_prepaid_eligible', models.BooleanField(default=False)),
                ('requires_project', models.BooleanField(default=False)),
                ('requires_department', models.BooleanField(default=False)),
                ('approval_required_above', models.DecimalField(blank=True, decimal_places=2, help_text='UGX threshold above which approval is required. NULL means always required.', max_digits=18, null=True)),
                ('branch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_credit_account', models.ForeignKey(blank=True, help_text='Default AP or cash account for the credit side of the journal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_credit', to='ledgers.account')),
                ('default_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_expense', to='ledgers.account')),
                ('default_tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_tax', to='ledgers.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_period_id', models.UUIDField(db_index=True, help_text='References ledgers.FiscalPeriod.id')),
                ('department', models.CharField(blank=True, db_index=True, max_length=120)),
                ('branch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('project', models.CharField(blank=True, db_index=True, max_length=120)),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='UGX budget allocation', max_digits=18)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, help_text='UGX consumed so far', max_digits=18)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='expense_accounting.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('employee', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=120)),
                ('project', models.CharField(blank=True, db_index=True, max_length=120)),
                ('cost_center', models.CharField(blank=True, db_index=True, max_length=120)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction currency amount (before tax)', max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='UGX equivalent of amount', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_base_amount', models.DecimalField(decimal_places=2, default=0, help_text='UGX equivalent of tax_amount', max_digits=18)),
                ('description', models.TextField()),
                ('expense_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=16)),
                ('approval_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=8)),
                ('created_by', models.UUIDField()),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='ledgers.currency')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='expense_accounting.expensecategory')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='ledgers.journalentry')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_reversals', to='ledgers.journalentry')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction currency net amount', max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='UGX net amount', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('project', models.CharField(blank=True, max_length=120)),
                ('cost_center', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_lines', to='ledgers.account')),
                ('expense_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expense_accounting.expensetransaction')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver', models.UUIDField(blank=True, db_index=True, null=True)),
                ('approval_level', models.PositiveSmallIntegerField(help_text='1=manager, 2=finance, 3=CFO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='expense_accounting.expensetransaction')),
            ],
            options={
                'ordering': ['approval_level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_reference', models.CharField(db_index=True, max_length=64)),
                ('employee', models.UUIDField(db_index=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='UGX equivalent', max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('merchant', models.CharField(max_length=255)),
                ('reconciled', models.BooleanField(db_index=True, default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_transactions', to='ledgers.currency')),
                ('expense_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='expense_accounting.expensetransaction')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepaidExpenseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_months', models.PositiveSmallIntegerField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Transaction currency', max_digits=18)),
                ('monthly_base_amount', models.DecimalField(decimal_places=2, help_text='UGX', max_digits=18)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remaining_base_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('next_run_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('amortizations_posted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_schedule', to='expense_accounting.expensetransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['expense_type', 'is_active'], name='expense_acc_expense_2b1461_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['branch', 'is_active'], name='expense_acc_branch_a8bae3_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['fiscal_period_id', 'department'], name='expense_acc_fiscal__69ad68_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['fiscal_period_id', 'branch'], name='expense_acc_fiscal__4cf0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebudget',
            index=models.Index(fields=['fiscal_period_id', 'project'], name='expense_acc_fiscal__37937f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['status', 'expense_date'], name='expense_acc_status_8efdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['branch', 'status'], name='expense_acc_branch_6f399a_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['department', 'expense_date'], name='expense_acc_departm_e0a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['project', 'expense_date'], name='expense_acc_project_13eb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['employee', 'status'], name='expense_acc_employe_d0c167_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['expense_transaction', 'status'], name='expense_acc_expense_d2bee5_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapproval',
            index=models.Index(fields=['approver', 'status'], name='expense_acc_approve_1d7a41_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatecardtransaction',
            index=models.Index(fields=['employee', 'reconciled'], name='expense_acc_employe_946c87_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatecardtransaction',
            index=models.Index(fields=['card_reference', 'transaction_date'], name='expense_acc_card_re_fa2c20_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaidexpenseschedule',
            index=models.Index(fields=['status', 'next_run_date'], name='expense_acc_status_03b0f4_idx'),
        ),
    ]
